[package]
name = "data-analysis"
version = "0.1.0"
authors = ["Josh Chesser <joshua.chesser@student.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
